name: checkov

on:
  pull_request:
  push:
    branches:
      - main    

jobs:
  scan:
    runs-on: ubuntu-latest 
    permissions:
      contents: read
      security-events: write
     
    steps:
    - uses: actions/checkout@v2
    
    - name: Run checkov 
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        api-key: ${{ secrets.BC_API_KEY }}
        repo-id: prisma/devsecops-workshop2
        directory: .  # hoặc code/ nếu folder code nằm trong đó
        output: sarif
        output-file-path: results.sarif
        prisma-api-url: https://app.sg.prismacloud.io
        
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      if: success() || failure()
      with:
        sarif_file: results.sarif
